repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      #- id: detect-aws-credentials
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-builtin-literals
      - id: check-ast
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
      - id: isort
        name: isort (cython)
        types: [cython]
        args: ["--profile", "black", "--filter-files"]
      - id: isort
        name: isort (pyi)
        types: [pyi]
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell
-   repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
